modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT license. See LICENSE.txt for a copy."

[[mods]]
    modId="simplebackpacks" 
    version="${version}"
    displayName="Simple Backpacks"
    authors="shroomdog27"
    description='''
    Adds simple four different tiered backpacks.
    '''

[[dependencies.simplebackpacks]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplebackpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
